### ISSUE TITLE
Reflect const-generics in refinements

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#482]
(via: https://github.com/flux-rs/flux/pull/481#discussion_r1297422785)

So this is the hard part. I've been thinking for a while about generic consts appearing in refinements. I think supporting that would be very cool.

This is related to global consts (e.g., `const N: i32 = 3`) which we do support inside refinements with `ExprKind:: ConstDefId`. I was thinking that we can maybe represent generic consts with the same variant. Then, we only need to be careful when encoding into fixpoint to differentiate between global consts, for which we assume a value, and generic consts which we leave opaque (we could also have a different variant in `ExprKind`). This change should be relatively simple and it would allow us to remove the `tracked_span_bug` here.

The next step would be to support const generics in our surface syntax. For that, the tricky part is name resolution. It shouldn't be that complicated though, we just need to track those names when desugaring and decide what to do with shadowing.

All this can go into a different PR.

_Originally posted by @nilehmann in https://github.com/flux-rs/flux/pull/481#discussion_r1297422785_

**Comment by nilehmann** [comment]
continuing the discussion here

> @nilehmann said:
> No, you can't specify _bounds_ on const generics (i.e., `I<N`). If you think about it, you end up needing arbitrary SMT in order to do that, that's why I think is really cool to be able to mention them in refinements, because you get it "for free"

> @ranjitjhala said:
> Interesting -- so then what's the point of quantifying over the `N`?
> 
> Strictly speaking you can do some lets say, _ad-hoc_ / "lightweight" arithmetic reasoning, e.g. the sort done in GHC's `Nat` solver, or stuff like this:
> 
> https://discourse.llvm.org/t/rfc-enforcing-bounds-safety-in-c-fbounds-safety/70854
> 
> Maybe that you can say things like you get passed in two arrays of the same length `N`?

Const generics are not very useful when used in types. So yeah, you can use them to say that two arrays have the same length (`fn foo<const N: usize>(x: [i32; N], y: [i32; N]`), but simple stuff that requires arithmetic can't be expressed, for example, `fn baz<const N: usize>(x: [i32; N], y: [i32; N + 1])` cannot be expressed because that requires a bound on `N` ensuring it doesn't overflow. There has been some work trying to support simple arithmetic via syntactic restrictions that won't require an SMT, but it hasn't been stabilized. 

Const generics are more useful when you want to do compile-time computations (multi-stage programming (?)). For example, you can do a compile-time *switch*:

```rust
fn bar<const N: u8>() {
    if N == 0 {
        ...
    } else if N == 1 {
       ...
    }
    ...
}
```

There are other more sophisticated stuff you can do at compile-time, like compile-time tables and such.

**Comment by nilehmann** [comment]
Just anecdotally, the other day I did a compile-time kmp table for a pattern I wanted to search

```rust
pub const fn kmp_table<const N: usize>(p: [u8; N]) -> [usize; N] {
    let m = p.len();
    let mut t = [0; N];

    let mut i = 1;
    let mut j = 0;
    while i < m {
        if p[i] == p[j] {
            t[i] = j + 1;
            i = i + 1;
            j = j + 1;
        } else if j == 0 {
            t[i] = 0;
            i = i + 1;
        } else {
            j = t[j - 1];
        }
    }
    t
}
```

**Comment by ranjitjhala** [comment]
Isn’t this done already by the const generics PR?

**Comment by nilehmann** [comment]
yes it is
