### ISSUE TITLE
Supporting dynamic trait objects

### ISSUE THREAD

**Issue by enjhnsn2** [flux-rs/flux#655]
As we discussed in the meeting earlier, it seems like everyone is interested in adding support for dynamic trait objects to Flux. To get the ball rolling, I put together a very simple test case (based off the Rust book dyn trait example: https://doc.rust-lang.org/rust-by-example/trait/dyn.html):
```Rust
#![allow(unused)]

struct Sheep {}
struct Cow {}


trait Animal {
    // Instance method signature
    fn noise(&self);
}

// Implement the `Animal` trait for `Sheep`.
impl Animal for Sheep {
    fn noise(&self) {
        println!("baaaaah!");
    }
}

// Implement the `Animal` trait for `Cow`.
impl Animal for Cow {
    fn noise(&self) {
        println!("moooooo!");
    }
}

fn make_two_noises(animal: &dyn Animal) {
    animal.noise();
    animal.noise();
}
```

This code currently fails to verify with the error message: 
`refinement of unsupported function` 
`this function contains unsupported features`

**Comment by nilehmann** [comment]
I was thinking we could implement it in a series of steps

1. Add support for `&dyn Trait` in `fhir` and `rty` but (gracefully) fail when calling a method on a dynamic object. This already adds value because it would allow us to trust (as opposed to ignore) code using `&dyn Trait`. Depending on how this goes, we would fail either during lowering or in the checker.
2. When calling a method on a dynamic object use the signature in the trait.
3. Use associated refinements to refine the signature in the trait.

Maybe there's not much of a gap between the steps, but we will see. 

For the first step, we should accept the following

```rust
#[flux::trusted]
fn make_two_noises(animal: &dyn Animal) {
    animal.noise();
    animal.noise();
}
```

**Comment by ranjitjhala** [comment]
I'll start on this next

**Comment by nilehmann** [comment]
I realized there was a step missing: create a dynamic object. This is done via an [unsized coercion ](https://doc.rust-lang.org/reference/type-coercions.html#unsized-coercions), aka, we are missing the following from the test case

```rust
fn main() {
    let sheep = Sheep {};
    make_two_noises(&sheep);
}
```

I don't know how this is represented in the mir or how hard it would be, but it should go somewhere after step 1.
