### ISSUE TITLE
Add support for `PlaceElem::ConstantIndex`

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#725]
The next big block of errors in `zkevm` is due to code like the below

```rust
fn test() -> usize {
    let [x, y] = [0, 1];
    x
}
```

I wonder if either you should handle this @nilehmann or whether instead this may be a good intro to the whole places/tree business for me to look at?

**Comment by nilehmann** [comment]
Is this a blocker? Looks tricky. I think it's using a [ConstantIndex](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/type.PlaceElem.html#variant.ConstantIndex) projection and I don't understand the semantics. I would have to investigate.

**Comment by nilehmann** [comment]
Ok, the complicated bit is that pattern matching on an array (which lowers to `ConstantIndex`) can be used to partially move out of it. We don't currently have a type that can represent this. For example,

```rust
// Non-copy type
struct S;

fn test(arr: [S; 2]) {
    // Move out first index
    let [x, ..] = arr;

    // arbitrary code in between
    let y  = 3;

    // Move out second index
    let [.., z] = arr;
}
```
After the first move we cant give a type to `arr`. One can only pattern match on an array with a fixed length (no const generic) so this looks a bit tractable. I see a couple of ways forward

1. Have a notion of an unfolded array where we can do strong updates on individual elements. Since you can only pattern match on a fixed-length array we could represent it as a vector of types that could be individually strong updated to `uninit`.
2. Only add support for `ConstantIndex` when the projected type is `Copy`. This would suffice for the original example.
3. Hack around it and don't update the type of the array after (partially) moving out of it.
