### ISSUE TITLE
Flux expects refinement of &mut Range<Idx> when given this refinement

### ISSUE THREAD

**Issue by vrindisbacher** [flux-rs/flux#831]
See here: https://github.com/vrindisbacher/flux-sandbox/blob/32bf3fd26a3c0d009869e83bf201cc6ee4dfbafb/src/range.rs#L100

Flux reports the following error: 

<img width="1415" alt="Screenshot 2024-10-01 at 3 38 41 PM" src="https://github.com/user-attachments/assets/e6599d93-22fa-4a4f-bfea-80dc5ebae2ab">

Even with a refinement of `&mut Range<Idx>`, the same error appears (see https://github.com/vrindisbacher/flux-sandbox/blob/56bf59f37853b6fa9d687c3b84043ced11016cb0/src/range.rs#L100)

<img width="1415" alt="Screenshot 2024-10-01 at 3 40 17 PM" src="https://github.com/user-attachments/assets/2bbbe891-25ad-4303-961d-779180755231">

**Comment by nilehmann** [comment]
What commit of flux are you using @vrindisbacher ? I can't reproduce. Running `cargo flux` on that commit gives me a different error

```rust
error[E0999]: implemented associated refinement `done` has an incompatible sort for trait
  --> src/range.rs:96:18
   |
96 | #[flux_rs::assoc(fn done(r: Range<Idx>) -> bool { r.start == r.end } )]
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Range<A::sort> -> bool`, found `Range<Idx::sort> -> bool`
```
which I can fix by using `A` as a name for the parameter instead of `Idx`

 (I'm preparing a fix that checks you are using the exact same generics, including names, as in the external definition which would hopefully make this a little bit less confusing)

**Comment by nilehmann** [comment]
![image](https://github.com/user-attachments/assets/f319b395-74bb-4c96-9b3a-168a6f0677d2)

**Comment by vrindisbacher** [comment]
I updated flux and was able to fix this. I didn't know that it had to match the external definition exactly. Thanks for the help.
